# Generated by Django 5.1 on 2024-11-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calorie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lipid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('glucid', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
